### ISSUE TITLE
 Could not find a valid gem 'yasb' (>= 0) in any repository

### ISSUE THREAD

**Issue by ssbarnea** [lebogan/yasb#1]
It seems that the documentation was written before publishing yasb :)
```
gem install yasb
ERROR:  Could not find a valid gem 'yasb' (>= 0) in any repository
```

**Comment by lebogan** [comment]
@ssbarnea 
Good catch. This was on a private repo server and I brain-farted the docs. Am updating and testing now. Please check back.
